version: '3.8'
networks:
  my-network:

services:
  notif:
    build: .
    ports:
      - "3000:3000"
    restart: always
    networks:
      - my-network
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    networks:
      - my-network
    ports:
      - "5672:5672"
      - "15672:15672"