version: '3.8'
networks:
  my-network:

services:
  notif:
    build: .
    ports:
      - "3000:3000"
    restart: always
    networks:
      - my-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics ping -q"]
      interval: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    networks:
      - my-network
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      retries: 5
